### ISSUE TITLE
Text in buttons is not exactly vertically aligned

### ISSUE THREAD

**Issue by meslater1030** [allenai/varnish-deprecated#174]
Right now, the Varnish button text is just slightly lower than the middle of the button vertically:

(screenshot from https://varnish.allenai.org/components/button/)

![Screen Shot 2020-08-13 at 1 49 43 PM](https://user-images.githubusercontent.com/10873798/90185647-e1ef0a80-dd6b-11ea-88bf-ba79dcba7906.png)

I think it should look like this:

![Screen Shot 2020-08-13 at 1 51 00 PM](https://user-images.githubusercontent.com/10873798/90185800-0d71f500-dd6c-11ea-88aa-abf6e063eb06.png)

I made the change in the second screenshot by specifying a `line-height` of 1.375 for the button. It looks like the `.ant-btn` class gives 1.375 for `line-height` but something is overriding that property to specify `initial` instead. I know it's a subtle distinction but it bothers my eyes and I suspect I won't be the only one.

**Comment by jonborchardt** [comment]
now just using antd
