### ISSUE TITLE
We no longer export the AI2 Banner.

### ISSUE THREAD

**Issue by codeviking** [allenai/varnish-deprecated#180]
We used to export the `<AI2Banner />` component, so that people who want the AI2 brand to be present, but don't want our full-fledged header, can use it.

We don't do so anymore, so it can't be used.

I'd expect to be able to do:

```
import { AI2Banner } from `@allenai/varnish`
```

**Comment by jonborchardt** [comment]
yes, we should export it more directly... (you can get to it via the lib imports)
we should consider:
```
import { Header } from `@allenai/varnish`
const {AI2Banner} = Header;
```

**Comment by codeviking** [comment]
@jonborchardt That doesn't work for me:

```
/usr/local/src/skiff/app/ui/src/App.tsx
TypeScript error in /usr/local/src/skiff/app/ui/src/App.tsx(18,9):
Property 'AI2Banner' does not exist on type 'HeaderProps'.  TS2339

    16 | import { PDFPage } from './pages';
    17 | 
  > 18 | const { AI2Banner } = Header;
       |         ^
    19 | 
    20 | const App = () => (
    21 |     <>
```

I tried that, and looked at the code. It doesn't look like we export it.

**Comment by jonborchardt** [comment]
no. i didnt mean to imply this worked, im saying I should make it work this way...

i think something like this this works:
import { AI2Banner} from '@allenai/varnish/es/header/AI2Banner';

ref #151

**Comment by jonborchardt** [comment]
now exported
