### ISSUE TITLE
We need to revize the copyright text antd appends to compiled JS.

### ISSUE THREAD

**Issue by codeviking** [allenai/varnish-deprecated#64]
In [this file](https://github.com/ant-design/antd-tools/blob/master/lib/getWebpackConfig.js#L198) the antd build tools append a banner to compiled code like so:

> Copyright 2015-present, Alipay, Inc.
> All rights reserved.

We'll need to modify this in the files we distribute ultimately, to reflect that some parts of the code are Copyright AI2.

We should ask Jenn what the final text should read.

**Comment by jonborchardt** [comment]
not relev anymore
