### ISSUE TITLE
Only update the demo site when a version is released, show the current version number and if possible link to old versions of the docs.

### ISSUE THREAD

**Issue by codeviking** [allenai/varnish-deprecated#74]
The Ant Demo site by default displays the current version in the top-right corner, and lets you navigate to old versions as well:

![image](https://user-images.githubusercontent.com/801451/82388133-a0112b00-99ed-11ea-8e00-f7fc3a7bc092.png)

Since we're now just running their site, I imagine we can do the same.  Right now the [Varnish](https://varnish.allenai.org) site doesn't display any of this. I'm not sure why.

We should restore this capability if possible. Also, when we do this we should switch the demo site to only be deployed when there's a new version released. Maybe it's just a step in `scripts/publish.py` instead of a Github workflow.

**Comment by jonborchardt** [comment]
i removed all of this to simplify v0

**Comment by jonborchardt** [comment]
not doing
